/** Trip data shapes. Generated files come from ../data/generated, hand-entered
 *  booking data lives in ../data/trip.json. */

export type LatLng = [number, number];

/* ---------- generated: the route, built and verified against OSRM ---------- */

export interface Poi {
  name: string;
  lat: number;
  lng: number;
  search: string;          // Google Maps query string — name, not coordinates
  cat: string;
  dwell: number;           // minutes
  ticket: boolean;
  hike: boolean;
  price: number;           // ISK
  note?: string | null;
  activity?: string | null;
  mx?: string;             // routing proxy key when the pin is off the road network
}

export interface Stop {
  loc: string;             // key into Itinerary["poi"]
  dwell: number;
}

export interface Day {
  date: string;            // "Oct 3"
  title: string;
  start: string;           // "08:00"
  stops: Stop[];
}

export interface Itinerary {
  planId: string;
  days: Day[];
  poi: Record<string, Poi>;
  keys: string[];
  dur: number[][];         // minutes, OSRM raw (pad ×1.15 for October)
  dist: number[][];        // km
  geo: Record<string, LatLng[]>;   // "from|to" -> road polyline
  isk_eur: number;
}

/* ---------- database: everything within 10 km of the roads we drive ---------- */

export type PlaceKind = "attraction" | "food" | "fuel" | "grocery" | "stay";

export interface Place {
  id: string;
  name: string;
  lat: number;
  lng: number;
  kind: PlaceKind;
  cat: string;
  /** [[km, dayIndex], ...] for EVERY day whose road passes within 10 km, nearest first.
   *  A list, not a single day — 1,400+ places sit on more than one day's route. */
  days: [number, number][];
  town: boolean;
  phone?: string;
  website?: string;
  address?: string;
  hours?: string;          // OSM volunteer data — often missing or stale
  email?: string;
  wheelchair?: string;
  wikidata?: string;
  planned?: boolean;       // attractions only: already a stop in the itinerary
  brand?: string;          // fuel and groceries
  cuisine?: string;
  vegetarian?: boolean;
  vegan?: boolean;
  self_service?: boolean;
  stars?: string;
}

export interface DaySummary {
  day: number;
  date: string;
  title: string;
  routeKm: number;
  counts: Record<string, number>;
  fuelOnRoute: number;
  longestFuelGapKm: number;
  longestFuelGapBetween: [string, string];
}

/* ---------- hand-entered: what we actually booked ---------- */

export interface Flight {
  direction: "out" | "home";
  airline: string;
  flightNo: string;
  from: string;            // IATA
  to: string;
  date: string;            // ISO "2026-10-02"
  depart: string;          // local "21:00"
  arrive: string;
  arriveDate?: string;     // set when the flight lands the next day
  fromName?: string;
  toName?: string;
  bookingRef?: string;
  terminal?: string;
  seats?: string;
  notes?: string;
}

/** Only what the app is allowed to know — the confirmation number, customer number,
 *  renter and price live in data/trip.json and Telegram. The road restrictions DO
 *  belong here: they are the thing worth reading while driving. */
export interface CarHire {
  model?: string;
  spec?: string;
  pickup: { place: string; date: string; time: string };
  dropoff: { place: string; date: string; time: string };
  restrictions?: {
    summary: string;
    bannedRoads: string[];
    penaltyISK: number;
    note?: string;
    routeVerified?: string;
  };
}

/** Only what the app is allowed to know. The full record — property, address,
 *  confirmation, phone, notes — stays in data/trip.json and in Telegram. */
export interface Booking {
  night: number;
  date: string;
  town: string;
  lat?: number;
  lng?: number;
}

export interface TourBooking {
  name: string;
  operator: string;
  date: string;            // ISO
  time: string;
  meetingPoint: string;
  bookingRef?: string;
  phone?: string;
  duration?: string;
  price?: number;
  notes?: string;
}

export interface Traveller {
  name: string;
  phone?: string;
  notes?: string;          // licence for driving, dietary, etc.
}

export interface TodoItem {
  what: string;
  owner: string;
  blocking: boolean;
}

/** What the APP sees. Generated by data/scripts/build_public.py from the full
 *  trip.json, with every identifier stripped — see that script for what is dropped
 *  and why. The real booking details live in Telegram, not on a deployed site. */
export interface Trip {
  title: string;
  flights: Flight[];
  car?: CarHire;
  bookings: Booking[];     // night, date, town and coordinates only
  tours: TourBooking[];
  emergency?: Record<string, string>;
}
